//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contract
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mec()
        {
            this.SeKvalifikujes = new HashSet<SeKvalifikuje>();
        }
    
        public int IdMeca { get; set; }
        public System.DateTime DatumOdrzavanja { get; set; }
        public string Kolo { get; set; }
        public string Rezultat { get; set; }
        public int StatistikaIdStatistike { get; set; }
        public Nullable<int> TerenIdTerena { get; set; }
        public int SePrijavljujeTurnirIdTurnira { get; set; }
        public long SePrijavljujeSudijaJMBG { get; set; }
    
        public virtual Statistika Statistika { get; set; }
        public virtual Teren Teren { get; set; }
        public virtual SePrijavljuje SePrijavljuje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeKvalifikuje> SeKvalifikujes { get; set; }
    }
}
