//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contract
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeKvalifikuje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SeKvalifikuje()
        {
            this.Mecs = new HashSet<Mec>();
        }

        public SeKvalifikuje(int turnirIdTurnira, int timIdTima)
        {
            TurnirIdTurnira = turnirIdTurnira;
            TimIdTima = timIdTima;
        }

        public int TurnirIdTurnira { get; set; }
        public int TimIdTima { get; set; }
    
        public virtual Turnir Turnir { get; set; }
        public virtual Tim Tim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mec> Mecs { get; set; }
    }
}
