//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contract
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trener : Ucesnik
    {
        public TipTrenera Tip { get; set; }
        public int BrojOsvojenihTitula { get; set; }
        public Nullable<int> TimIdTima { get; set; }
    
        public virtual Tim Tim { get; set; }
    }
}
